name: Android Release CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hail-Release-APK
          path: app/build/outputs/apk/release/*.apk
